# ==================================================
# Site Settings
# ==================================================
title: Christopher Priebe
email: christophermpriebe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

footer_text: >
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>. For additional credits, see <a href="/credits/">this</a>.
display_last_updated_date: true

# ==================================================
# User Profile
# ==================================================
profile:
  first_name: Christopher
  middle_name: M.
  last_name: Priebe
  title: Ph.D. Student
  affiliation: University of California San Diego
  location: La Jolla, CA
  image: /assets/images/headshot.jpg

# ==================================================
# Resume
# ==================================================

resume_home_icon: true
resume_avatar: true
resume_title: Graduate Student Researcher
resume_social_links: true
resume_executive_summary: >
    I am a Ph.D. student in the Department of Computer Science and Engineering at the University of California San Diego. My research is an interplay of compilers, machine learning, and systems.
resume_looking_for_work: true
resume_section_experience: true
resume_section_education: true
resume_section_publications: false 
resume_section_projects: true

# ==================================================
# Front Matter Defaults
# ==================================================
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      nav: false
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "single_column_page"
      show_title: true


# ==================================================
# Jekyll Scholar
# ==================================================

scholar:
  last_name: [Priebe]
  first_name: [Christopher]

  style: apa
  locale: en

  source: /_bibliography/
  bibtex_filters: [latex, smallcaps, superscript]

  query: "@*"
  group_by: year
  group_order: descending

  bibliography_template: bib


# ==================================================
# Collections
# ==================================================

collections:
  history:
    output: false
  news:
    defaults:
      layout: base
    output: true
    permalink: /:collection/:title/
  projects:
    defaults: 
      layout: base
    output: true
    permalink: /:collection/:title/
  resume:
    output: false

# ==================================================
# Jekyll Settings
# ==================================================

# plugins 
# plugins:
#   - jekyll-feed

# includes & excludes
include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor

# ==================================================
# Library Versions
# ==================================================
